import test from 'node:test';
import assert from 'node:assert/strict';
import { createEditor } from '../packages/keyboard/src/editor.js';
import { createKeyboard, createPinyinEngine, createLayout, resolveTouch, toT9 } from '../packages/keyboard/src/index.js';
import lexicon from '../packages/keyboard/data/lexicon.js';

const bounds = { x: 0, y: 0, width: 960, height: 266 };
const tick = () => new Promise((resolve) => setImmediate(resolve));
const engine = createPinyinEngine(lexicon);
test('licensed offline dictionary provides useful Chinese words and T9 alternatives', () => {
  assert.equal(engine.size, 65125);
  assert.ok(engine.query('nihao').some((candidate) => candidate.text === '你好'));
  assert.ok(engine.query(toT9('zhongguo'), { layout: 't9' }).some((candidate) => candidate.text === '中国'));
  const rows = engine.query('shi');
  assert.equal(rows[0].exact, true);
  assert.equal(new Set(rows.map((row) => row.text)).size, rows.length);
  assert.deepEqual(engine.query(''), []);
});
test('editor deletes emoji clusters, combining marks, flags and moves at cluster boundaries', () => {
  const editor = createEditor('a👨‍👩‍👧‍👦🇨🇳e\u0301');
  editor.deleteBackward();
  assert.equal(editor.snapshot().text, 'a👨‍👩‍👧‍👦🇨🇳');
  editor.deleteBackward();
  editor.move(-1);
  editor.insert('中');
  assert.equal(editor.snapshot().text, 'a中👨‍👩‍👧‍👦');
  assert.equal(createEditor('ab', 2).insert('c'), false);
});
test('confirm commits candidates, cancel preserves original, layout and editor sessions are independent', async () => {
  const keyboard = createKeyboard({ engine });
  const cancelled = keyboard.open({ bounds, value: '原文' });
  keyboard.press('2');
  keyboard.cancel();
  assert.deepEqual(await cancelled, { confirmed: false, text: '原文' });
  const confirmed = keyboard.open({ bounds, layout: 'qwerty', value: '' });
  for (const key of 'nihao') keyboard.press(key);
  await tick();
  keyboard.select(keyboard.snapshot().candidates.findIndex((row) => row.text === '你好'));
  keyboard.setMode('english');
  keyboard.press('A');
  keyboard.press('确定');
  assert.deepEqual(await confirmed, { confirmed: true, text: '你好A' });
  const reopened = keyboard.open({ bounds });
  assert.equal(keyboard.snapshot().composition, '');
  assert.equal(keyboard.snapshot().text, '');
  keyboard.dispose();
  assert.equal((await reopened).confirmed, false);
  assert.throws(() => keyboard.open({ bounds }), /disposed/);
});
test('stale async results never update a new session or changed mode', async () => {
  const pending = [];
  const keyboard = createKeyboard({ engine: { query(input) { return new Promise((resolve) => pending.push({ input, resolve })); } } });
  const first = keyboard.open({ bounds });
  keyboard.press('2');
  const second = keyboard.open({ bounds });
  await first;
  pending[0].resolve([{ text: '旧', id: 1, consumed: 1 }]);
  await tick();
  assert.deepEqual(keyboard.snapshot().candidates, []);
  keyboard.press('3');
  keyboard.setMode('number');
  pending[1].resolve([{ text: '旧', id: 2, consumed: 1 }]);
  await tick();
  assert.deepEqual(keyboard.snapshot().candidates, []);
  keyboard.cancel();
  await second;
});
test('held candidate stays fixed when a query returns and cancellation releases it', async () => {
  let resolve;
  const keyboard = createKeyboard({ engine: { query(input) { return input.length === 1 ? [{ id: 1, text: '一', consumed: 1 }] : new Promise((accept) => { resolve = accept; }); } } });
  const result = keyboard.open({ bounds });
  keyboard.press('2');
  await tick();
  keyboard.holdCandidate(0);
  keyboard.press('3');
  resolve([{ id: 2, text: '二', consumed: 2 }]);
  await tick();
  assert.equal(keyboard.snapshot().candidates[0].text, '一');
  keyboard.releaseCandidate();
  assert.equal(keyboard.snapshot().text, '一');
  keyboard.cancel();
  await result;
});
test('touch gaps are corrected for letters while movement, outside release and control gaps cancel', async () => {
  const geometry = createLayout({ ...bounds, mode: 'pinyin', layout: 'qwerty' });
  const key = geometry.keys[0];
  assert.equal(resolveTouch(geometry.keys, { x: key.x - 1, y: key.y + 10 }).value, 'q');
  const control = geometry.keys.find((item) => item.value === '⌫');
  assert.equal(resolveTouch(geometry.keys, { x: control.x + control.width + 1, y: control.y + 10 }), null);
  const keyboard = createKeyboard({ engine });
  const result = keyboard.open({ bounds, mode: 'english', layout: 'qwerty' });
  const point = { x: key.x + 8, y: key.y + 8, id: 2 };
  keyboard.touchStart(point);
  keyboard.touchMove({ ...point, x: point.x + 30 });
  keyboard.touchEnd(point);
  assert.equal(keyboard.snapshot().text, '');
  keyboard.touchStart(point);
  keyboard.touchEnd({ ...point, x: -1 });
  assert.equal(keyboard.snapshot().text, '');
  keyboard.touchStart(point);
  keyboard.touchEnd(point);
  assert.equal(keyboard.snapshot().text, 'q');
  keyboard.cancel();
  await result;
});
test('long deletion timers stop on cancel, close and unload', async () => {
  const tasks = new Map();
  let next = 0;
  const timers = { setTimeout(fn) { tasks.set(++next, fn); return next; }, clearTimeout(id) { tasks.delete(id); } };
  const keyboard = createKeyboard({ engine, timers });
  const result = keyboard.open({ bounds, mode: 'english', value: 'abc' });
  const key = keyboard.snapshot().keys.find((item) => item.value === '⌫');
  const point = { id: 1, x: key.x + 10, y: key.y + 10 };
  keyboard.touchStart(point);
  const timer = [...tasks.values()][0];
  tasks.clear();
  timer();
  assert.equal(keyboard.snapshot().text, 'ab');
  assert.equal(tasks.size, 1);
  keyboard.touchCancel();
  assert.equal(tasks.size, 0);
  keyboard.touchStart(point);
  keyboard.dispose();
  assert.equal(tasks.size, 0);
  await result;
});
test('newline, max length, inset, outside dismiss and instances obey host contracts', async () => {
  const insets = [];
  const a = createKeyboard({ engine, onInset: (value) => insets.push(value) });
  const b = createKeyboard({ engine });
  const pa = a.open({ bounds, mode: 'english', presentation: 'inset', multiline: true, maxLength: 2 });
  const pb = b.open({ bounds, mode: 'number', outsideAction: 'dismiss' });
  a.press('A'); a.press('↵'); a.press('B');
  b.press('2');
  assert.equal(a.snapshot().text, 'A\n');
  assert.equal(b.snapshot().text, '2');
  b.outside();
  assert.equal((await pb).confirmed, false);
  a.press('确定');
  assert.equal((await pa).text, 'A\n');
  assert.deepEqual(insets, [bounds, null]);
});

test('moving a held candidate and switching mode cancel selection', async () => {
  const keyboard = createKeyboard({ engine });
  const result = keyboard.open({ bounds, layout: 'qwerty' });
  keyboard.press('n'); keyboard.press('i');
  await tick();
  keyboard.holdCandidate(0, { id: 1, x: 150, y: 50 });
  keyboard.moveCandidate({ id: 1, x: 180, y: 50 });
  keyboard.releaseCandidate();
  assert.equal(keyboard.snapshot().text, '');
  keyboard.holdCandidate(0);
  keyboard.setMode('english');
  keyboard.releaseCandidate();
  assert.equal(keyboard.snapshot().text, '');
  keyboard.cancel();
  await result;
});

test('multiline preview follows cursor and joining insertion remains at a valid boundary', async () => {
  const keyboard = createKeyboard({ engine });
  const result = keyboard.open({ bounds, value: '第一行\n第二行', mode: 'english', multiline: true });
  assert.equal(keyboard.snapshot().displayText, '第二行│');
  keyboard.press('←');
  assert.equal(keyboard.snapshot().displayText, '第二│行');
  keyboard.cancel();
  await result;
  const editor = createEditor('👧');
  editor.move(-1);
  editor.insert('👨‍');
  editor.deleteBackward();
  assert.equal(editor.snapshot().text, '');
});

test('malformed engine results and broken observers leave a usable isolated session', async () => {
  const keyboard = createKeyboard({ engine: { query() { return [{ text: 'bad', consumed: -1 }, { text: '好', consumed: 1 }]; } } });
  const result = keyboard.open({ bounds });
  keyboard.subscribe((state) => { if (state.visible) throw new Error('observer'); });
  keyboard.press('2');
  await tick();
  const snapshot = keyboard.snapshot();
  assert.equal(snapshot.candidates.length, 1);
  snapshot.candidates[0].text = 'changed';
  snapshot.bounds.width = 0;
  snapshot.keys[0].value = 'changed';
  assert.equal(keyboard.snapshot().bounds.width, 960);
  assert.equal(keyboard.snapshot().keys[0].value, '2');
  keyboard.press('确定');
  assert.deepEqual(await result, { confirmed: true, text: '好' });
});
